### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VSatwika**
### Description

Update screenshot image. 

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by wasimreja** [comment]
@VSatwika you have to change the image

**Comment by VSatwika** [comment]
May I please know how I can change the image and to what?
Thank you very much.

**Comment by VSatwika** [comment]
google

**Comment by wasimreja** [comment]
i guess you have microsoft edge too. open book finder on the browser. use `ctrl + shift + s` keyboard shortcut. select full page.
create a new issue, upload (drag & drop) images to it, copy the image URL and paste it into `README.md` file.

**Pull request closed without merging**
