### PR TITLE
Added prefers-color-scheme for a working dark mode & minor style tweaks

### PR DESCRIPTION
**Pull request by jackwebdev**
### Description

Using the css "prefers-color-scheme" tag fr people with OS that can automatically enable a dark mode you will see a nice dark theme for Book Finder. 

Changes:
- Added extra margin bottom to the results container.
- Added a dark theme that automatically turns on with css "prefers-color-scheme" media feature. 
- Added extra styles to make the dark theme suitable with the rest of the design.
- Fixed the input bar not being fully rounded. This was noticeable when turning to a dark theme.

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
It's not togglable but it's a start with the addition of a dark theme. See issue #7. 

## Add relevant screenshot or video (if any)
Screenshot of dark theme on:
Screenshot 2022-10-01 at 7 21 07 pm

### CODE REVIEW

**Comment by jackwebdev** [comment]
Fixed a merge conflict. I hope I did that right!

**Comment by jackwebdev** [comment]
Updated to work with latest changes and included the new navbar. 

Screenshot 2022-10-07 at 8 51 26 am

**Comment by wasimreja** [comment]
great! raise the pr in hacktoberfest branch

**Comment by jackwebdev** [comment]
> great! raise the pr in hacktoberfest branch

Done! See #111.

**Pull request closed without merging**
