### PR TITLE
Added Voice Method

### PR DESCRIPTION
**Pull request by DevilzzNikhil**
### Description

I have button of Listen so that user can listen the information about book like name of book and author and description

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#34  has been solved 

 @wasimreja  please check and merge for hactoberfest

### CODE REVIEW

**Comment by wasimreja** [comment]
not working

**Comment by DevilzzNikhil** [comment]
@wasimreja  can u tell on which is and browser your are working it has some problem in brave browser don't know why but works fine in all and it wait for some time approx 2  3 sec so can u check again as it works prfine properly in my i can share u the recording also

**Comment by wasimreja** [comment]
i'm using firefox and microsoft edge. not working on both of the browsers

**Comment by DevilzzNikhil** [comment]
I don't know why but it is working on me it's your wish to merge or not but check on chrome

**Comment by wasimreja** [comment]
could you fix that?

**Comment by DevilzzNikhil** [comment]
> could you fix that?

@wasimreja  it is not the error by the way the browser which supports it is working on them i am not sure why u r facing issue in firefox

image
It works on these browser not no why not working in yours but it s working in mine and many more laptops i have checked from the vercel deployment

**Comment by wasimreja** [comment]
> > could you fix that?
> 
> @wasimreja it is not the error by the way the browser which supports it is working on them i am not sure why u r facing issue in firefox
> 
> image It works on these browser not no why not working in yours but it s working in mine and many more laptops i have checked from the vercel deployment

okay will merge, keep the button style as read now

**Comment by DevilzzNikhil** [comment]
thnks for that i will  make changes
@wasimreja

**Comment by wasimreja** [comment]
> thnks for that i will make changes @wasimreja

raise the pr in hacktoberfest branch

**Comment by DevilzzNikhil** [comment]
@wasimreja  please tell how to do that i if sync your fork then it will delete my commits then what to do

**Pull request closed without merging**
