### PR TITLE
sematic header tag added

### PR DESCRIPTION
**Pull request by nishtha53**
### Description

(Write your answer here.)

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

- I have added header sematic HTML tag as mentioned in description. Please check my PR.

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
You don't need to include your vs code settings file in the PR. Otherwise this looks good. Remove the extra file and then wait for a review from the repo owner.

**Comment by nishtha53** [comment]
Is it fine now @EmmaDawsonDev

**Review by wasimreja — CHANGES_REQUESTED** [review]
delete your vs code settings file and raise the pr.

**Comment by nishtha53** [comment]
@wasimreja vscode settings page is removed. PR raised. Please approve it.

**Pull request merged**
