### PR TITLE
added a loading spinner #93

### PR DESCRIPTION
**Pull request by SOUMYADIP76**
### Description

Added a loading spinner #93

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Review by wasimreja — CHANGES_REQUESTED** [review]
- JQuery Ajax loading spinner only on first request
- Change spinner color as read button

**Comment by SOUMYADIP76** [comment]
Yea I actually noticed that but couldn't find the way to solve it ... Can you please help me to resolve the issue . Can you please tell me what and where should I add the code to resolve the issue of loader as it is rolling once at the 1st time of reload of the page @wasimreja

**Comment by wasimreja** [comment]
Okay, I'm merging your pr. Just change the spinner color.

**Comment by wasimreja** [comment]
Okay, I'm merging your pr.

**Pull request merged**
