### PR TITLE
Update style.css for dark theme

### PR DESCRIPTION
**Pull request by Devrajsinh03**
### Description
Changed background color of dark theme so that the image above search box looks good

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## relevant screenshot or video (if any)

- before
Screenshot 2022-10-14 at 1 39 22 PM

- after
Screenshot 2022-10-14 at 1 38 34 PM

(Add here)

### CODE REVIEW

**Review by wasimreja — CHANGES_REQUESTED** [review]
enhance the entire dark ui

**Comment by Devrajsinh03** [comment]
@wasimreja can accept this pr for now? I will enhance it in another pr.

**Comment by wasimreja** [comment]
make necessary changes, i'll merge

**Comment by Devrajsinh03** [comment]
@wasimreja 👍

**Pull request closed without merging**
