### PR TITLE
added footer with hover effect

### PR DESCRIPTION
**Pull request by Ayushbajpai19**
I have added the hover effect in the footer section as well as the footer with the copyright part.

### CODE REVIEW

**Comment by Ayushbajpai19** [comment]
Can you please merge my PR, this my first hacktoberfest

**Comment by Ayushbajpai19** [comment]
Kindly check the about us section and let me know if you want any changes.

**Comment by wasimreja** [comment]
@Ayushbajpai19 few changes need to be done.
- remove social icons
- text align to `center`
- change font family to `"Comfortaa", cursive`
- change copyright text to Copyright © 2022 BookFinder
- change padding to `1rem 1rem`
- change hover color to `#bfbfbf,` add transition `all 0.3s linear` and add homepage link

**Comment by wasimreja** [comment]
you are not supposed to add about page to this pr

**Comment by Ayushbajpai19** [comment]
I know brother, can you review it and tell me if its okay , also I wasn't able to push it to that particular issue

**Comment by Ayushbajpai19** [comment]
I ll do all the changes mentioned above

**Comment by Ayushbajpai19** [comment]
You don't want social media icons?

**Comment by wasimreja** [comment]
> You don't want social media icons?

no, keep it minimalist.

**Comment by wasimreja** [comment]
@Ayushbajpai19 first make the necessary changes to footer, i'll merge it. then work on the about page and raise a new pr.

**Review by wasimreja — COMMENTED** [review]
@Ayushbajpai19 first make the necessary changes to footer, i'll merge it. then work on the about page and raise a new pr.

**Comment by wasimreja** [comment]
@Ayushbajpai19 are you working on this or should i assign this to someone else?

**Comment by Ayushbajpai19** [comment]
The last commit that i did was for footer only, kindly check it

**Pull request closed without merging**
