### PR TITLE
Feature/add 404

### PR DESCRIPTION
**Pull request by zanottipaolo**
### Description
Hi! 👋🏻
For Hacktoberst 2022 I thought to make a 404 error page not found to this website (with a nice animated image) and to add .gitignore file.
If you don't want to merge it is also fine just to add the label 'hacktoberfest-accepted'. ✅
Hope you will enjoy it! ✌🏻

### Checklist
- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
New pull request 🆕

## Add relevant screenshot or video (if any)
file-not-found

### CODE REVIEW

**Review by wasimreja — CHANGES_REQUESTED** [review]
when a user types any book name that is not found, it shows book not found message, add the animated image on no book found response. write book instead of page, remove go home button and it would be better if you could use another animated image

**Comment by zanottipaolo** [comment]
Okay, I will do it today! 🙂--
Paolo Zanotti

**Comment by zanottipaolo** [comment]
Okay, I will do it today! 🙂

**Comment by zanottipaolo** [comment]
Hi @wasimreja 👋🏻
I think now it's okay based on what you said.

Hope you will enjoy it! ✌🏻

**Comment by wasimreja** [comment]
great! please resolve conflicts and raise a pr

**Comment by zanottipaolo** [comment]
> great! please resolve conflicts and raise a pr

Done.

**Review by zanottipaolo — COMMENTED** [review]
Refactor code

**Pull request merged**
