### PR TITLE
Designed About Us page a bit

### PR DESCRIPTION
**Pull request by Shreyan-12345**
### Description

(Write your answer here.)

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by Shreyan-12345** [comment]
pls chack and merge it @wasimreja

**Comment by Shreyan-12345** [comment]
@wasimreja @devwasim pls merge it

**Comment by wasimreja** [comment]
@Shreyan-12345 don't change the illustration.

**Review by wasimreja — CHANGES_REQUESTED** [review]
keep title about us as it is. add margin bottom. don't change the illustration. rest is okay.

**Comment by Shreyan-12345** [comment]
pls check the last commit @wasimreja @devwasim

**Pull request closed without merging**
