### PR TITLE
Navbar is improved

### PR DESCRIPTION
**Pull request by Ritu-2001**
improving navbar changes are done

### Description

(Write your answer here.)

### Checklist

- [ ] I am making a proper pull request, not spam.
- [ ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by Ritu-2001** [comment]
Please check it and merge my PR

**Comment by wasimreja** [comment]
not up to the mark.

**Comment by Ritu-2001** [comment]
@wasimreja  ok i am trying to make it better plss give  me some time

**Comment by Ritu-2001** [comment]
Screenshot (162)

**Comment by Ritu-2001** [comment]
Add the ss of present styling is it fine ?? or need to improve

**Comment by wasimreja** [comment]
you can work on other issues.

**Pull request closed without merging**
