### PR TITLE
changed the background of home page

### PR DESCRIPTION
**Pull request by Vanshiii203**
### Description

changed the background of home page

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

issue #77 

## Add relevant screenshot or video (if any)

Screenshot (463)

### CODE REVIEW

**Review by wasimreja — CHANGES_REQUESTED** [review]
@Vanshiii203 there is some issues with the background. also after search results are not showing. did you clone main branch?
 
Book Finder — Mozilla Firefox 05-10-2022 12_47_25

**Comment by Vanshiii203** [comment]
> @Vanshiii203 there is some issues with the background. also after search results are not showing. did you clone main branch?
> 
> Book Finder — Mozilla Firefox 05-10-2022 12_47_25

Yes

**Comment by Vanshiii203** [comment]
@wasimreja Should I create another PR??

**Comment by wasimreja** [comment]
@Vanshiii203 clone the hacktoberfest branch not main branch then change the background and raise pr

**Comment by Vanshiii203** [comment]
> @Vanshiii203 clone the hacktoberfest branch not main branch then change the background and raise pr

okay!

**Pull request closed without merging**
